name: Wrklow que implementa condicionales # Define el nombre del workflow

env: # (Opcional) Permite definir variables de entorno a nivel de workflow.
  VARIABLE_GLOBAL: Bancolombia

on: # Trigger del workflow
  # La ejecución del workflow se activa cuando
  # Se realiza un push en la rama main
  push:
    branches:
      - main
  # Se ejecuta manualmente
  workflow_dispatch:

# Agrupa los jobs dentro del workflow
jobs:
  # ID del job
  Job-ejecucion-manual:
    # Condición que ejecuta el job si el evento trigger no es manual (Uso del contexto github)
    if: ${{ github.event_name == 'workflow_dispatch' }}
    # Nombre del job
    name: Job ejecución manual
    # SO donde se correrá GH actions
    runs-on: ubuntu-latest

    # Agrupa los pasos dentro del job
    steps:
      # Nombre del step
      - name: Imprimir
        # Aquí se pueden definir las variables del ambiente (Opcional)
        env:
          MI_VARIABLE_1: Hola mundo - Mi Primer Job
        # Corre la siguiente instrucción
        run: echo "${{env.MI_VARIABLE_1}} - ${{env.VARIABLE_GLOBAL}}" #(Uso del contexto env)

  Job-ejecucion-push:
    # Condición que ejecuta el job si el evento trigger no es manual (Uso del contexto github)
    if: ${{ github.event_name != 'workflow_dispatch' }}
    name: Job ejecución push
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir
        env:
          MI_VARIABLE_2: Hola mundo - Mi Segundo Job
        # Corre la siguiente instrucción
        run: echo "$MI_VARIABLE_2 - $VARIABLE_GLOBAL"
