name: workflow adicionar cualquier etiqueta a un issue
on:
  issue_comment:
    types: [created]
# env:
#   ISSUE_URL: ${{ github.event.issue.html_url }}
#   USER_COMMENT: ${{ github.event.comment.user.login }}
#   NUMBER: ${{ github.event.issue.number }}
#   COMMENT: ${{ github.event.comment.body }}
jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Setup GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        
      - name: Generate a token of Github APP
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_ADMIN_GITHUB }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_ADMIN_GITHUB }}

      - name: Extraer información y verificar permisos
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
        run: |
          if [[ "$COMMENT_BODY" =~ ^/add-label\ (.*)$ ]]; then
            LABEL_NAME=${BASH_REMATCH[1]}

            if [[ ${VAR_USERS_REVIEWERS,,} =~ ${USER_COMMENT,,} ]]; then
            
            # Verificar permisos del usuario
            PERMISSIONS=$(gh api -X GET "repos/$REPO_OWNER/$REPO_NAME/collaborators/$COMMENT_AUTHOR/permission" | jq -r '.permission')
            if [[ "$PERMISSIONS" == "admin" || "$PERMISSIONS" == "write" ]]; then
              echo "LABEL_NAME=$LABEL_NAME" >> $GITHUB_ENV
            else
              echo "El usuario $COMMENT_AUTHOR no tiene permisos paraagregar etiquetas."
              exit 1  # Detener el workflow si no hay permisos
            fi
          fi

      - name: Agregar etiqueta
        if: env.LABEL_NAME != ''
        run: |
          gh issue edit $ISSUE_NUMBER --add-label "$LABEL_NAME"