name: workflow adicionar cualquier etiqueta a un issue
on:
  issue_comment:
    types: [created]
# env:
#   ISSUE_URL: ${{ github.event.issue.html_url }}
#   USER_COMMENT: ${{ github.event.comment.user.login }}
#   NUMBER: ${{ github.event.issue.number }}
#   COMMENT: ${{ github.event.comment.body }}
jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Setup GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        
      
      - name: Extraer información y verificar permisos
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
        run: |
          if [[ "$COMMENT_BODY" =~ ^/add-label\ (.*)$ ]]; then
            LABEL_NAME=${BASH_REMATCH[1]}

            if [[ ${VAR_USERS_REVIEWERS,,} =~ ${USER_COMMENT,,} ]]; then
              echo "LABEL_NAME=$LABEL_NAME" >> $GITHUB_ENV
            else
              gh issue comment $ISSUE_NUMBER --body "El usuario $COMMENT_AUTHOR no tiene permisos para agregar etiquetas."
            fi
          fi

      - name: Agregar etiqueta
        if: env.LABEL_NAME != ''
        run: |
          gh issue edit $ISSUE_NUMBER --add-label "$LABEL_NAME"