name: Matrix worklow # Define el nombre del workflow

on: # Trigger del workflow
  [push, pull_request] # Eventos que activan la ejecución del workflow

# Agrupa los jobs dentro del workflow
jobs:
  # ID del job
  Mi-primer-job:
    # Nombre del job
    name: Mi primer job
    # SOs donde correrá GH actions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]

    # Agrupa los pasos dentro del job
    steps:
      # Nombre del step
      - name: Imprimir
        # Aquí se pueden definir las variables del ambiente
        env:
          MI_VARIABLE_1: Hola mundo - Mi Primer Job - Matriz de Estrategia
        # Corre la siguiente instrucción
        run: echo "$MI_VARIABLE_1"

