name: Worklow Multiple Trigger # Define el nombre del workflow

env: # (Opcional) Permite definir variables de entorno a nivel de workflow.
  VARIABLE_GLOBAL: Bancolombia

on: # Trigger del workflow
  # La ejecución del workflow se activa cuando
  # Se realiza un push en la rama main
  push: 
    branches:
      - main
  # Se crea, se sincronizsa o se reabre un pull request
  pull_request:
    types: [opened, synchronize, reopened]
  # Se abre o se etiqueta un issue.
  issues:
    types:
      - opened
      - labeled
  # Se ejecuta manualmente
  workflow_dispatch:
    inputs:
      notificacion:
          description: 'Notificación nivel'
          required: true
          default: '2'
          type: choice
          options:
          - 0
          - 1
          - 2
  # Se programa su ejecución(Todos los días a las 10:15 p.m)
  schedule:
    - cron:  '15 22 * * *'

# Agrupa los jobs dentro del workflow
jobs:
  # ID del job
  Mi-primer-job:
    # Condición que ejecuta el job si el evento trigger no es manual
    if: ${{ github.event_name != 'workflow_dispatch' }}
    # Nombre del job
    name: Mi primer job
    # SO donde se correrá GH actions
    runs-on: ubuntu-latest

    # Agrupa los pasos dentro del job
    steps:
      # Nombre del step
      - name: Imprimir
        # Aquí se pueden definir las variables del ambiente
        env:
          MI_VARIABLE_1: Hola mundo - Mi Primer Job - Trigger no es manual
        # Corre la siguiente instrucción
        run: echo "$MI_VARIABLE_1 - $VARIABLE_GLOBAL"

  Mi-segundo-job:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Mi segundo job
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir
        env:
          MI_VARIABLE_2: Hola mundo - Mi Segundo Job - Trigger manual
        run: echo "$MI_VARIABLE_2 - $VARIABLE_GLOBAL"

